pong:
	gcc -Wall -Werror -Wextra -o pong.out  pong.c
	./pong.out
pong_interactive:
	gcc -Wall -Werror -Wextra -o pong_interactive.out  pong_interactive.c -lncurses
	./pong_interactive.out
clean:
	rm -rf *.out